### ISSUE TITLE
GroupBy column option

### ISSUE THREAD

**Issue by k010** [MoonStorm/trNgGrid#142] opened 2015-01-13 14:31 UTC
Can you consider to add the funcionability to group columns Eg.
```html
<thead>
<tr>
<th field-name="person.name" display-name="Name" group-by="Person"></th>
<th field-name="person.lastname" display-name="Lastname" group-by="Person"></th>
<th field-name="company.name" display-name="Company Name" group-by="Company"></th>
<th field-name="company.address" display-name="Company Address" group-by="Company"></th>
</tr>
</thead>
```
Or customize more than one ```<tr>``` in HEAD and BODY to add rowspan, colspan 

What do you think ??
It's would be very useful 
Thanks !!

**Comment by MoonStorm** [comment] 2015-01-19 00:11
An angular style full templating support for all the table sections is in the works as we speak. It'll take a while though.

**Comment by chachou29** [comment] 2015-02-20 11:20
Same need for me ... 
Thank you !!!!!!!

**Comment by MoonStorm** [comment] 2015-03-04 22:38
Duplicate of #92

**Closed by MoonStorm** 2015-03-04 22:38 UTC
