### ISSUE TITLE
Display-Name not displaying. What am I doing wrong?

### ISSUE THREAD

**Issue by toddhd** [MoonStorm/trNgGrid#199] opened 2015-07-28 18:30 UTC
I just found and started using trNgGrid today, so maybe this is a "total noob" issue, but so far I have a pretty basic table hooked up to sample data with only 24 rows in it.

My HTML looks like this:
```html
<table tr-ng-grid="" items="users" page-items="5" fields="['img','firstName','lastName','department','activationDate','expirationDate']">
    <thead>
        <tr>
            <th field-name="img" display-name="" enable-filtering="false" enable-sorting="false" cell-width="55px" display-align="center"></th>
            <th field-name="firstName" display-name="First Name" display-align="left"></th>
            <th field-name="lastName" display-name="Last Name" display-align="left"></th>
            <th field-name="department" display-name="Department" display-align="left"></th>
            <th field-name="activationDate" display-name="Activation" display-align="left" display-format="date:'MM-dd-yyyy'"></th>
            <th field-name="expirationDate" display-name="Expiration" display-align="left" display-format="date:'MM-dd-yyyy'"></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td field-name="img">
                <img src="{{gridItem.img}}" style="border-radius: 4px;" />
            </td>
        </tr>
    </tbody>
</table>
```

But when I view the table, I don't see any header names at all?

![image](https://cloud.githubusercontent.com/assets/177686/8939820/8f7a08ac-351b-11e5-94ef-317d12e5192d.png)

What did I do wrong?

**Comment by MoonStorm** [comment] 2015-07-29 17:56
That markup looks fine to me. Could you please attempt to reproduce the problem in a Plunker. You can fork [this one](http://plnkr.co/edit/JCLrJD?p=preview) if you want.

**Comment by toddhd** [comment] 2015-07-29 18:04
It's the angular version. Changing it to v1.4.2 is what's killing it. I don't suppose there's a simple fix/work-around? (Probably not, but I need to ask).

**Comment by MoonStorm** [comment] 2015-07-29 18:12
Yeah, just saw your post in the 1.4 thread. No, I don't have an easy fix for it at this time. I need to understand what's changed in 1.4 that's causing this issue. Didn't spot anything in their breaking changes list that would affect the code in the grid.

**Comment by toddhd** [comment] 2015-07-29 22:44
OK, thank you. For what it is worth, I've tried out about half a dozen tables/grids this week and yours is by far the one I like the most. It's easy to use, looks good, and just makes sense to me. Everything else just seems to clunky to me. So here's to hoping you're able to get it working again.

Sounds like some sort of localization issue, but that's not terribly helpful.

**Comment by MoonStorm** [comment] 2015-07-29 23:19
Thanks for your words. That's exactly the reason why I started working on this one. I got too frustrated trying to use the other ones in one of my projects.

**Comment by MoonStorm** [comment] 2015-07-31 06:31
duplicate of #198

**Closed by MoonStorm** 2015-07-31 06:31 UTC
