### ISSUE TITLE
`table-striped` table with large data set renders slow while using `ngAnimate`

### ISSUE THREAD

**Issue by jitendersandhu** [MoonStorm/trNgGrid#225] opened 2016-01-08 20:39 UTC
Hi,

I have a client-side pagination on the table with `max page size 200`, while navigating between pages with page size of `100` or more, the table renders very slow.
The problem is only there while using `Angular-animate version <= 1.4.4`, the performance improves if upgraded to `angular-animate` more recent versions `1.4.5` or the most-recent `1.4.8`.

Also, i have noticed that even though i am setting the `selection-mode` as `None` , `tr-ng-grid` is still adding `ng-click="toggleItemSelection(gridItem, $event)"` and 
`ng-class="{'active':gridOptions.selectedItems.indexOf(gridItem) >= 0, }"` to each row (`tr` element). As per my understanding, these are only required if the row selection is enabled.

Here are the two plunkers i have created with two different versions of angular-animate:
`Angular-animate v1.4.4` - [plunker-example-1](http://plnkr.co/edit/51EwGDDkIJ7VNAkP0ps5?p=preview)
`Angular-animate v1.4.8` - [plunker-example-2](http://plnkr.co/edit/kmxF4EujNfFO1s1bjgn9?p=preview)

Any help would be much appreciated. Thanks!

**Comment by MoonStorm** [comment] 2016-01-08 23:48
Wow, I'm amazed it works now with ngAnimate. Some people have reported problems with this combination in the past. (e.g. #191). That thing is a PITA.

You're right regarding that ``ng-click``, however we didn't want to complicate the default template, as many people have been overriding it. So the idea was to keep the logic inside ``toggleItemSelection`` and decide there what to do.

**Comment by jitendersandhu** [comment] 2016-01-12 01:16
@MoonStorm Thanks for the quick reply!

I agree it's a compatibility issue with `Angular-animate v1.4.4`, in particular. But for me it's a trade-off between using `UI-Select` and slow-performance of `tr-ng-grid` table as with latest versions of angular-animate, `UI-Select` is having some issue.

Anyways, on further digging, i found that the slowness is mostly caused by animation on `table-striped` class from bootstrap (included for zebra-striping). Removing it, improves performance.

So, until there is a proper fix, a workaround is to add `ng-class-odd` and add custom class to `tr` for `Zebra-striping` instead of `table-striped` class on `table` tag.
Something like - `ng-class-odd="'table-striped-custom'"`. Here is the updated [plunker](http://plnkr.co/edit/51EwGDDkIJ7VNAkP0ps5?p=preview).
Thanks!

**Comment by MoonStorm** [comment] 2016-01-12 17:43
``table-striped`` isn't used by default by the grid. I believe it was interfering with selections back in the day.  The in-code comment says:
``
TrNgGrid.tableCssClass = "tr-ng-grid table table-bordered table-hover"; // at the time of coding, table-striped is not working properly with selection
``

Looking at bootstrap CSS, I found only this declaration involving ``table-striped``:
```
.table-striped > tbody > tr:nth-of-type(odd) {
  background-color: #f9f9f9;
}
```
I can see how this could affect performance when it comes to animating the newly enumerated rows as their style is constantly changing until the list of displayed items is exhausted. This together with maybe browser performance problems when it comes to this selector could be the culprit. Chrome was apparently having a performance issue with this but apparently it was fixed, not sure if released as well:
https://code.google.com/p/chromium/issues/detail?id=461878 
https://code.google.com/p/chromium/issues/detail?id=475720

Not sure about how we could avoid the performance problems caused by this selector. At the end of the day, the grid is by default a Bootstrap painted component, but with the ability of changing that with whatever CSS people would want.

**Comment by jitendersandhu** [comment] 2016-08-24 23:12
@MoonStorm Thanks for the explanation!

I know it's been a long time, but just now when i was going through open issues for `trNgGrid`, i noticed your reply. If you want, you can go ahead and close this issue as it seems to be a compatibility issue. Thanks! 👍

**Closed** 2017-02-07 19:15 UTC
Labels: compatibility issue
