### ISSUE TITLE
Dataset sorting in Chrome

### ISSUE THREAD

**Issue by AgentMulders** [MoonStorm/trNgGrid#95] opened 2014-09-16 13:22 UTC
I found that if I bind a dataset that's already sorted I get some bizarre behaviour from the grid in the Chrome browser. It swaps around the first row with another one lower down. This doesn't happen in IE or Firefox, and it's forced me to specify sorting on the grid when I bind the data in the Angular controller. It's not a deal-breaker but it's annoying.

**Comment by divan** [comment] 2015-01-08 12:00
I was also experienced this issue with Chrome. Finally, I found that this issue is present when using Angular 1.2.28 - see the fork from MoonStorm's fiddle: http://jsfiddle.net/vxy9nuL2/
With 1.3.5 everything seems to work fine.

**Comment by giedrycz** [comment] 2015-01-08 14:54
Great, thanks very much for letting me know.

**Comment by divan** [comment] 2015-01-08 16:53
Just a note - I've edited my initial comment - 1.2.9 is an earlier version than 1.2.28, so this issue still probably should be investigated. Switching to Angular 1.2.9 is a workaround, but doesn't tell anything about the cause.

**Comment by MoonStorm** [comment] 2015-01-08 18:45
Managed to replicate it. @divan you're right.  In Angular 1.2.9. everything is fine, tried in 1.2.28 and items are all over the place. This seems to happen when a sort-by field is not set. I was relying on a behavior in an edge case that has changed. My bad. 

A fix will soon come your way.

**Comment by MoonStorm** [comment] 2015-01-11 05:57
Fixed in 3.0.4

**Closed** 2015-01-11 05:57 UTC
Labels: bug, released

**Comment by divan** [comment] 2015-01-11 12:41
Works perfectly with 3.0.4.
Thanks MoonStorm, hope your moving over the ocean was fine :)

**Comment by MoonStorm** [comment] 2015-01-11 16:54
It was thank you very much :) A bit stressful but everything turned out just fine. The most annoying thing is having to build a credit history... again. Without it everything has to come straight from my pocket.

Looking for a job at the moment...
