### ISSUE TITLE
Multiple filter by column

### ISSUE THREAD

**Issue by k010** [MoonStorm/trNgGrid#143] opened 2015-01-14 17:35 UTC
Am working with multiple filters or complex filters per columns, the idea is create a directive and it's can use like a plugin for trNgGrid (or i hope so) and i need the way to pass an array or object to ```gridOptions.gridColumnDefs[column].filter``` so the watcher listening for change in the value, and call setFilter and dispatch the sever-call with this options. 

The first thing i found is for example in the watch of columnOptions.filter if i pass an array and add new values (to the array) the watcher don't fires because don't have the option ```true``` in the 3er parameter in the watch. 

```javascript
scope.$watch("columnOptions.filter", function (newValue, oldValue) {
    if (newValue !== oldValue) {
      controller.setFilter(columnOptions.fieldName, newValue);
    }
});
```
If i add this options, temporaly works, the watch fires and call a setFilter function, but i think am forget something more to add or change in the core.

So the point is, what i need to know if there's another way to implement or pass multiples values for filter per column or if you will to consider the possibility to implement multiple values.

Because if you are in server-side yo can build something like this:

```javascript
// Eg. TemplateCell object
...
displayName: 'Name'
fieldName: 'name'
filter: ['John', 'Marie', 'Ana']
...
```

```html
<table tr-ng-grid='' items='data' fields='visibleFields' on-data-required='fn(currentPage, pageItems, filterBy, filterByFields, orderBy, orderByReverse)' page-items='pagination.itemsPerPage' total-items='pagination.totalItems'>
...
</table>
``` 

```javascript
var fn = function(currentPage, pageItems, filterBy, filterByFields, orderBy, orderByReverse) {
   // filterByFields {name: ['John', 'Marie', 'Ana']}
  // build server query function... (...url?filters={name:['John', 'Marie', 'Ana']}&sort=id...)
}
```
And pass to server this options and get the response.

What do you think ? 

Thanks man !!!

**Comment by MoonStorm** [comment] 2015-01-19 00:06
I believe client-side I'm relying on the angular 'filter' filter to perform the search. I don't think that filter supports arrays, but as I'm being forced to move further and further away from angular's out-of-the-box behaviors, this idea might go in at some point. That would require a bit of work on the UI side as well, e.g. a combo with a list of values.

**Comment by MoonStorm** [comment] 2015-03-06 21:04
Duplicate of #107.

**Closed by MoonStorm** 2015-03-06 21:04 UTC
Labels: deferred, enhancement
