### ISSUE TITLE
Any way to add column totals in footer?

### ISSUE THREAD

**Issue by ChrissDeGrece** [MoonStorm/trNgGrid#99] opened 2014-09-19 09:54 UTC
Tried to add extra footer rows but they are ignored, is there any recommended way to add column totals?

Thanks

**Comment by akubyshkin** [comment] 2015-01-07 11:24
When the next major version will be approximately released?

**Comment by MoonStorm** [comment] 2015-03-06 22:19
@akubyshkin  You already know the answer to that question :smile: 

Duplicate of #92.

**Closed by MoonStorm** 2015-03-06 22:19 UTC
